FROM quay.io/jitesoft/debian:10-slim

LABEL org.opencontainers.image.source https://github.com/mood-mapping-muppets/repo

RUN apt-get update && \
    apt-get install -y \
      git build-essential \
      python3 python3-dev python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/coviddash

COPY . /opt/coviddash

RUN echo "/opt/coviddash" > \
    /usr/local/lib/python3.7/dist-packages/coviddash.pth

RUN ln -sf /usr/bin/python3.7 /usr/bin/python
