FROM tiangolo/uwsgi-nginx-flask:python3.7

LABEL org.opencontainers.image.source https://github.com/mood-mapping-muppets/repo

RUN python3 -m pip install --upgrade \
    pip==20.2.4 \
    setuptools==50.3.2 \
    poetry==1.1.4

WORKDIR /app

COPY dashboard/pyproject.toml dashboard/poetry.lock ./

RUN poetry export \
      --without-hashes > requirements.txt && \
    python3 -m pip install -r requirements.txt && \
    rm requirements.txt && \
    rm -rf /root/.cache

COPY dashboard ./
